Repository six-goguma/Algo-Hive-FE, pull requests merged in 2025-01, with the labels that each got.

#2 issue#1 템플릿 적용
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/pull_request_template.md
Labels: 📖 Docs

#3 Issue, PR 템플릿 적용
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/pull_request_template.md
Labels: 📖 Docs

#15 issue#05 tsconfig, viteconfig & 절대경로 설정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/app/routes/router.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📦 Environment

#11 issue#10
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  src/shared/service/config/instance.ts
Labels: 🚀 Deploy

#26 issue#04 - Prettier, eslint 설정
  .prettierignore
  .prettierrc
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: 📦 Environment

#27 issue#8 - router 설정 및 header 설정
  package.json
  pnpm-lock.yaml
  src/app/routes/router.tsx
  src/pages/error/_assets/index.ts
  src/pages/error/components/index.ts
  src/pages/error/index.ts
  src/pages/error/ui/ErrorPage.tsx
  src/pages/error/ui/index.ts
  src/pages/index.ts
  src/pages/post-edit/apis/index.ts
  src/pages/post-edit/components/index.ts
  src/pages/post-edit/data/index.ts
  src/pages/post-edit/hooks/index.ts
  src/pages/post-edit/index.ts
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-edit/ui/index.ts
  src/shared/components/index.ts
  src/shared/components/layouts/header/Header.tsx
  src/shared/components/layouts/header/index.ts
  src/shared/components/layouts/index.ts
  src/shared/constants/RouterPath.ts
  src/shared/constants/index.ts
  src/shared/styles/index.ts
  src/shared/utils/dynamic-path/DynamicPath.ts
  src/shared/utils/dynamic-path/index.ts
  src/shared/utils/index.ts
  src/shared/utils/scroll-to-top/ScrollToTop.ts
  src/shared/utils/scroll-to-top/index.ts
  src/widgets/index.ts
  src/widgets/layouts/Layout.tsx
  src/widgets/layouts/index.ts
  src/widgets/post/index.ts
Labels: ✨ Feature, 📦 Environment

#29 issue#28 - prettier 포맷팅 변경사항 수정 및 기타 설정
  .gitignore
  .prettierignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package.json
  public/favicon.ico
  public/vite.svg
  src/App.tsx
  src/app/routes/router.tsx
  src/pages/code-review/ui/CodeReviewPage.tsx
  src/pages/error/ui/ErrorPage.tsx
  src/pages/main/ui/MainPage.tsx
  src/pages/post-edit/ui/PostEditPage.tsx
  src/shared/components/layouts/header/Header.tsx
  src/shared/config/axios-instance.ts
  src/shared/constants/RouterPath.ts
  src/shared/lib/axios-instance.ts
  src/shared/lib/query-client.ts
  src/shared/providers/application-provider.tsx
  src/shared/themes/global/common/Button.tsx
  src/shared/themes/global/features/global-style.ts
  src/shared/utils/dynamic-path/DynamicPath.ts
  src/shared/utils/scroll-to-top/ScrollToTop.ts
  src/widgets/layouts/Layout.tsx
  vite.config.ts
Labels: ♻️ Refactoring, 📦 Environment

#30 issue#14 - header ui 구현
  .prettierrc
  src/main.tsx
  src/shared/_assets/logo.png
  src/shared/components/container/Container.tsx
  src/shared/components/container/index.ts
  src/shared/components/index.ts
  src/shared/components/layouts/header/Header.tsx
  src/shared/config/axios-instance.ts
  src/shared/index.ts
  src/shared/providers/application-provider.tsx
  src/shared/styles/index.ts
  src/shared/styles/reset.css
  src/shared/styles/variants/breakpoints.ts
  src/shared/styles/variants/index.ts
  src/shared/themes/global/common/Button.ts
  src/shared/themes/global/features/global-style.ts
  src/widgets/layouts/Layout.tsx
Labels: 🎨 Design

#32 issue#12 메인페이지 ui 구현
  src/pages/main/components/index.ts
  src/pages/main/components/tabs/Tabs.tsx
  src/pages/main/components/tabs/index.ts
  src/pages/main/mock/index.ts
  src/pages/main/mock/post-list.ts
  src/pages/main/ui/MainPage.tsx
  src/shared/components/index.ts
  src/shared/components/layouts/header/ui/Header.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/mock/index.ts
  src/shared/hooks/mock/useGetMockData.ts
  src/shared/index.ts
  src/shared/themes/global/features/global-style.ts
  src/shared/utils/date-format/DateFormat.ts
  src/shared/utils/date-format/index.ts
  src/shared/utils/index.ts
  src/widgets/container/Container.tsx
  src/widgets/container/index.ts
  src/widgets/grid/Grid.tsx
  src/widgets/grid/index.ts
  src/widgets/index.ts
  src/widgets/post-cards/PostCards.tsx
  src/widgets/post-cards/SkeletonPostCards.tsx
  src/widgets/post-cards/index.ts
  src/widgets/view/LoadingView.tsx
  src/widgets/view/index.ts
Labels: ✨ Feature, 🎨 Design

#33 issue#21 post 작성 및 수정 modal 구현
  src/pages/post-edit/data/index.ts
  src/pages/post-edit/data/post-detail.ts
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-write/ui/PostWritePage.tsx
  src/widgets/modals/PostModal.tsx
  src/widgets/modals/index.ts
  src/widgets/post-cards/PostCards.tsx
  src/widgets/post-cards/SkeletonPostCards.tsx
Labels: ✨ Feature, 🎨 Design

#34 issue#17 채팅 페이지 UI 구현
  src/pages/chat/components/index.ts
  src/pages/chat/components/input/ChatInputBox.tsx
  src/pages/chat/components/input/index.ts
  src/pages/chat/components/message/ChatMessage.tsx
  src/pages/chat/components/message/ChatMessageList.tsx
  src/pages/chat/components/message/index.ts
  src/pages/chat/components/modal/SetUserNameModal.tsx
  src/pages/chat/components/modal/index.ts
  src/pages/chat/components/room/ChatRoomInsideSection.tsx
  src/pages/chat/components/room/ChatRoomList.tsx
  src/pages/chat/components/room/ChatRoomListItem.tsx
  src/pages/chat/components/room/ChatRoomSection.tsx
  src/pages/chat/components/room/index.ts
  src/pages/chat/components/user/ChatUserList.tsx
  src/pages/chat/components/user/ChatUserListItem.tsx
  src/pages/chat/components/user/ChatUserSection.tsx
  src/pages/chat/components/user/index.ts
  src/pages/chat/index.ts
  src/pages/chat/mock/mockChatMessageList.ts
  src/pages/chat/mock/mockOnlineUserList.ts
  src/pages/chat/mock/mockRooms.ts
  src/pages/chat/ui/ChatPage.tsx
Labels: 🎨 Design

#37 issue#17 채팅방 ui 일부 수정
  src/pages/chat/components/input/ChatInputBox.tsx
  src/pages/chat/components/modal/SetUserNameModal.tsx
  src/pages/chat/components/room/ChatRoomInsideSection.tsx
  src/pages/chat/components/room/ChatRoomList.tsx
  src/pages/chat/components/room/ChatRoomSection.tsx
  src/pages/chat/components/user/ChatUserSection.tsx
  src/pages/chat/mock/index.ts
  src/pages/chat/ui/ChatPage.tsx
Labels: 😡 Bug Fix

#35 issue#23 커스텀 Toast 구현
  src/shared/hooks/index.ts
  src/shared/hooks/toast/index.ts
  src/shared/hooks/toast/useCustomToast.tsx
  src/shared/providers/application-provider.tsx
Labels: 🎨 Design

#36 issue#24 에러페이지 구현
  src/pages/error/_assets/error.png
  src/pages/error/_assets/index.ts
  src/pages/error/components/index.ts
  src/pages/error/ui/ErrorPage.tsx
Labels: 🎨 Design

#52 issue#22 코드리뷰 페이지 UI 작성
  src/pages/code-review/components/codeinput/CodeInputBox.tsx
  src/pages/code-review/components/codeinput/index.ts
  src/pages/code-review/components/index.ts
  src/pages/code-review/components/result/ReviewResult.tsx
  src/pages/code-review/components/result/index.ts
  src/pages/code-review/ui/CodeReviewPage.tsx
Labels: 🎨 Design

#53 issue#19 게시글 수정 페이지 UI 작성
  pnpm-lock.yaml
  src/pages/post-edit/ui/PostEditPage.tsx
  src/shared/components/index.ts
  src/shared/components/post-form/PostTitle.tsx
  src/shared/components/post-form/index.ts
  src/shared/components/post-form/post-content/hooks/index.ts
  src/shared/components/post-form/post-content/index.ts
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/shared/components/post-form/post-content/ui/index.ts
  src/shared/components/post-form/post-content/utils/index.ts
  src/shared/components/post-form/post-content/utils/uploadFile.ts
  src/shared/components/post-form/post-tag/data/index.ts
  src/shared/components/post-form/post-tag/data/tag-data.ts
  src/shared/components/post-form/post-tag/hooks/index.ts
  src/shared/components/post-form/post-tag/hooks/useTagSelection.ts
  src/shared/components/post-form/post-tag/index.ts
  src/shared/components/post-form/post-tag/ui/PostTag.tsx
  src/shared/components/post-form/post-tag/ui/index.ts
Labels: 🎨 Design
