Repository six-goguma/Algo-Hive-FE, pull requests merged in 2025-02, with the labels that each got.

#40 issue#16 마이 페이지 UI 구현
  src/pages/mypage/components/index.ts
  src/pages/mypage/components/my-post/MyPostSection.tsx
  src/pages/mypage/components/my-post/index.ts
  src/pages/mypage/components/profile/SkeletonProfileSection.tsx
  src/pages/mypage/components/profile/UserProfileSection.tsx
  src/pages/mypage/components/profile/index.ts
  src/pages/mypage/components/tabs/Tabs.tsx
  src/pages/mypage/components/tabs/index.ts
  src/pages/mypage/data/exampleprofile.png
  src/pages/mypage/data/index.ts
  src/pages/mypage/data/mockMyPostList.ts
  src/pages/mypage/data/mockUserProfile.ts
  src/pages/mypage/index.ts
  src/pages/mypage/ui/Mypage.tsx
Labels: 🎨 Design

#56 issue#55 메인페이지 ui 수정
  package.json
  pnpm-lock.yaml
  src/main.tsx
  src/pages/chat/apis/chat-rooms.api.ts
  src/pages/chat/apis/chat-rooms.type.ts
  src/pages/chat/apis/index.ts
  src/pages/chat/hooks/index.ts
  src/pages/chat/hooks/useGetChatRooms.ts
  src/pages/chat/ui/ChatPage.tsx
  src/pages/main/apis/index.ts
  src/pages/main/apis/post-list.api.ts
  src/pages/main/apis/post-list.type.ts
  src/pages/main/components/index.ts
  src/pages/main/components/navigate-button/NavigateButton.tsx
  src/pages/main/components/navigate-button/index.ts
  src/pages/main/components/post-list/PostList.tsx
  src/pages/main/components/post-list/index.ts
  src/pages/main/components/skeleton/ButtonSkeleton.tsx
  src/pages/main/components/skeleton/index.ts
  src/pages/main/data/index.ts
  src/pages/main/data/post-list.ts
  src/pages/main/hooks/index.ts
  src/pages/main/hooks/useGetPosts.ts
  src/pages/main/mock/index.ts
  src/pages/main/ui/MainPage.tsx
  src/pages/mypage/ui/Mypage.tsx
  src/shared/components/layouts/header/components/login-section/LoginSection.tsx
  src/shared/components/layouts/header/components/navigate-menu/NavigateMenu.tsx
  src/shared/components/layouts/header/components/signup-section/EmailSection.tsx
  src/shared/components/layouts/header/components/signup-section/NicknameSection.tsx
  src/shared/components/layouts/header/components/signup-section/PasswordSection.tsx
  src/shared/components/layouts/header/ui/Header.tsx
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/shared/components/post-form/post-content/utils/index.ts
  src/shared/components/post-form/post-content/utils/uploadFile.ts
  src/shared/config/api-error.ts
  src/shared/config/axios-instance.ts
  src/shared/config/index.ts
  src/shared/lib/axios-instance.ts
  src/shared/lib/http-instance.ts
  src/shared/lib/index.ts
  src/shared/service/config/index.ts
  src/shared/service/config/instance.ts
  src/shared/service/index.ts
  src/shared/styles/index.ts
  src/shared/styles/reset.css
  src/shared/styles/variants/breakpoints.ts
  src/shared/themes/global/common/Button.ts
  src/shared/themes/global/features/global-style.ts
  src/shared/types/http-instance.type.ts
  src/shared/types/index.ts
Labels: 😡 Bug Fix, ✨ Feature, 🎨 Design

#61 issue#60 전체 ui 수정
  src/pages/chat/components/modal/SetUserNameModal.tsx
  src/pages/chat/components/user/ChatUserSection.tsx
  src/pages/chat/ui/ChatPage.tsx
  src/pages/mypage/components/my-post/MyPostSection.tsx
  src/pages/mypage/components/profile/UserProfileSection.tsx
  src/widgets/grid/Grid.tsx
Labels: 🎨 Design

#58 issue#20 게시물 작성페이지 UI 구현
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-write/ui/PostWritePage.tsx
  src/shared/components/post-form/PostTitle.tsx
  src/shared/components/post-form/index.ts
  src/shared/components/post-form/post-button/index.ts
  src/shared/components/post-form/post-button/ui/PostButtons.tsx
  src/shared/components/post-form/post-button/ui/index.ts
  src/shared/components/post-form/post-content/ui/BlockNoteStyles.tsx
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/shared/components/post-form/post-tag/hooks/useTagSelection.ts
  src/shared/components/post-form/post-tag/ui/PostTag.tsx
  src/shared/components/post-form/post-title/index.ts
  src/shared/components/post-form/post-title/ui/PostTitle.tsx
  src/shared/components/post-form/post-title/ui/index.ts
Labels: 🎨 Design

#65 issue#41 메인페이지 기능구현
  src/pages/main/components/index.ts
  src/pages/main/components/skeleton/ButtonSkeleton.tsx
  src/pages/main/components/skeleton/index.ts
  src/pages/main/components/tabs/Tabs.tsx
  src/pages/main/ui/MainPage.tsx
  src/shared/components/index.ts
  src/shared/components/pagination/Pagination.tsx
  src/shared/components/pagination/index.ts
  src/shared/utils/index.ts
  src/shared/utils/text-overflow/TextOverflow.ts
  src/shared/utils/text-overflow/index.ts
  src/widgets/post-cards/PostCards.tsx
Labels: ✨ Feature, 📡 API

#66 issue#42 마이페이지 기능구현
  src/pages/mypage/apis/delete-user.api.ts
  src/pages/mypage/apis/delete-user.type.ts
  src/pages/mypage/apis/index.ts
  src/pages/mypage/apis/post-user.api.ts
  src/pages/mypage/apis/post-user.type.ts
  src/pages/mypage/apis/profile.api.ts
  src/pages/mypage/apis/profile.type.ts
  src/pages/mypage/apis/user-nickname.api.ts
  src/pages/mypage/apis/user-nickname.type.ts
  src/pages/mypage/components/my-post/MyPostSection.tsx
  src/pages/mypage/components/profile/SkeletonProfileSection.tsx
  src/pages/mypage/components/profile/UserProfileSection.tsx
  src/pages/mypage/components/tabs/Tabs.tsx
  src/pages/mypage/hooks/index.ts
  src/pages/mypage/hooks/useGetPostUser.ts
  src/pages/mypage/hooks/useGetProfile.ts
  src/pages/mypage/schema/index.ts
  src/pages/mypage/schema/mypage.ts
  src/pages/mypage/ui/Mypage.tsx
  src/shared/components/layouts/header/apis/login.api.ts
  src/shared/components/layouts/header/components/login-section/LoginSection.tsx
  src/shared/components/layouts/header/components/navigate-menu/NavigateMenu.tsx
  src/shared/components/layouts/header/hooks/index.ts
  src/shared/components/layouts/header/hooks/useGetLogout.ts
  src/shared/components/layouts/header/ui/Header.tsx
  src/shared/service/config/instance.ts
  src/shared/utils/index.ts
  src/shared/utils/storage/authStorage.ts
Labels: ✨ Feature, ♻️ Refactoring, 📡 API

#69 issue#43 채팅페이지 기능 구현
  package.json
  pnpm-lock.yaml
  src/pages/chat/apis/chat-rooms.api.ts
  src/pages/chat/apis/chat-rooms.type.ts
  src/pages/chat/apis/chat-ws.api.ts
  src/pages/chat/apis/index.ts
  src/pages/chat/components/index.ts
  src/pages/chat/components/input/ChatInputBox.tsx
  src/pages/chat/components/input/index.ts
  src/pages/chat/components/message/ChatMessage.tsx
  src/pages/chat/components/message/ChatMessageList.tsx
  src/pages/chat/components/message/index.ts
  src/pages/chat/components/modal/SetUserNameModal.tsx
  src/pages/chat/components/modal/index.ts
  src/pages/chat/components/room/ChatRoomInside.tsx
  src/pages/chat/components/room/ChatRoomInsideSection.tsx
  src/pages/chat/components/room/ChatRoomList.tsx
  src/pages/chat/components/room/ChatRoomListItem.tsx
  src/pages/chat/components/room/ChatRoomSection.tsx
  src/pages/chat/components/room/index.ts
  src/pages/chat/components/user/ChatUserList.tsx
  src/pages/chat/components/user/ChatUserListItem.tsx
  src/pages/chat/components/user/ChatUserSection.tsx
  src/pages/chat/components/user/index.ts
  src/pages/chat/hooks/index.ts
  src/pages/chat/hooks/useCreateChatRoom.ts
  src/pages/chat/hooks/useGetChatRooms.ts
  src/pages/chat/index.ts
  src/pages/chat/mock/index.ts
  src/pages/chat/mock/mockChatMessageList.ts
  src/pages/chat/mock/mockOnlineUserList.ts
  src/pages/chat/mock/mockRooms.ts
  src/pages/chat/ui/ChatPage.tsx
  src/shared/service/config/index.ts
  src/shared/service/config/wsclient.ts
  vite.config.ts
Labels: ✨ Feature, 📡 API

#70 issue#44 AI 코드리뷰 페이지 기능 구현
  src/pages/code-review/apis/code-review.apis.ts
  src/pages/code-review/apis/code-review.type.ts
  src/pages/code-review/apis/index.ts
  src/pages/code-review/components/codeinput/CodeInputBox.tsx
  src/pages/code-review/components/result/ReviewResult.tsx
  src/pages/code-review/hooks/index.ts
  src/pages/code-review/hooks/useCodeReview.ts
  src/pages/code-review/index.ts
  src/pages/code-review/ui/CodeReviewPage.tsx
Labels: ✨ Feature, 📡 API

#73 issue#72 채팅페이지에 email 연동
  src/pages/chat/ui/ChatPage.tsx
Labels: 😡 Bug Fix

#86 issue#45 게시글 상세페이지 기능 구현
  src/pages/post-detail/apis/post-comments.api.ts
  src/pages/post-detail/apis/post-comments.type.ts
  src/pages/post-detail/apis/post-detail.api.ts
  src/pages/post-detail/components/post-comments/CommentList.tsx
  src/pages/post-detail/components/post-comments/PostComments.tsx
  src/pages/post-detail/components/post-contents/PostContents.tsx
  src/pages/post-detail/components/post-info/PostInfo.tsx
  src/pages/post-detail/hooks/index.ts
  src/pages/post-detail/hooks/useLikeStatus.ts
  src/pages/post-detail/hooks/usePostComments.ts
  src/pages/post-detail/hooks/usePostDetail.ts
  src/pages/post-detail/styles/BlockNoteDetailStyles.tsx
  src/pages/post-detail/styles/index.ts
  src/pages/post-detail/ui/PostDetailPage.tsx
  src/pages/post-detail/ui/SkeletonPostDetail.tsx
  src/shared/components/post-form/post-tag/data/tag-data.ts
  src/shared/components/post-form/post-tag/ui/PostTag.tsx
  src/shared/service/config/instance.ts
  vite.config.ts
Labels: ✨ Feature

#87 issue#81 게시글 작성, 수정 페이지 오류 해결
  src/pages/post-edit/apis/post-edit.api.ts
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-edit/ui/SkeletonPostEditPage.tsx
  src/pages/post-write/apis/post-write.api.ts
  src/pages/post-write/ui/PostWritePage.tsx
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/shared/components/post-form/post-tag/ui/PostTag.tsx
  src/widgets/modals/PostModal.tsx
Labels: 😡 Bug Fix

#90 issue#88 코드리뷰 게시글 형식 수정 & 게시글 삭제 기능 수정
  src/pages/code-review/components/codeinput/CodeInputBox.tsx
  src/pages/post-detail/apis/post-detail.api.ts
  src/pages/post-detail/components/post-info/PostInfo.tsx
Labels: 😡 Bug Fix, ♻️ Refactoring

#92 issue#91 게시글 작성/수정 페이지 이미지 업로드 오류 수정
  src/pages/post-detail/apis/post-detail.type.ts
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-write/apis/post-write.api.ts
  src/pages/post-write/apis/post-write.type.ts
  src/pages/post-write/ui/PostWritePage.tsx
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/widgets/modals/PostModal.tsx
Labels: 😡 Bug Fix, ♻️ Refactoring

#93 develop 개발 상황 반영
  package.json
  pnpm-lock.yaml
  src/pages/chat/ui/ChatPage.tsx
  src/pages/code-review/components/codeinput/CodeInputBox.tsx
  src/pages/post-detail/apis/post-comments.api.ts
  src/pages/post-detail/apis/post-comments.type.ts
  src/pages/post-detail/apis/post-detail.api.ts
  src/pages/post-detail/apis/post-detail.type.ts
  src/pages/post-detail/components/post-comments/CommentList.tsx
  src/pages/post-detail/components/post-comments/PostComments.tsx
  src/pages/post-detail/components/post-contents/PostContents.tsx
  src/pages/post-detail/components/post-info/PostInfo.tsx
  src/pages/post-detail/hooks/index.ts
  src/pages/post-detail/hooks/useLikeStatus.ts
  src/pages/post-detail/hooks/usePostComments.ts
  src/pages/post-detail/hooks/usePostDetail.ts
  src/pages/post-detail/styles/BlockNoteDetailStyles.tsx
  src/pages/post-detail/styles/index.ts
  src/pages/post-detail/ui/PostDetailPage.tsx
  src/pages/post-detail/ui/SkeletonPostDetail.tsx
  src/pages/post-edit/apis/post-edit.api.ts
  src/pages/post-edit/ui/PostEditPage.tsx
  src/pages/post-edit/ui/SkeletonPostEditPage.tsx
  src/pages/post-write/apis/post-write.api.ts
  src/pages/post-write/apis/post-write.type.ts
  src/pages/post-write/ui/PostWritePage.tsx
  src/shared/components/post-form/post-content/ui/PostContent.tsx
  src/shared/components/post-form/post-tag/data/tag-data.ts
  src/shared/components/post-form/post-tag/ui/PostTag.tsx
  src/shared/service/config/instance.ts
  src/widgets/modals/PostModal.tsx
  vite.config.ts
Labels: 🚀 Deploy
